[package]
name = "InitiaStdlib"
version = "1.0.0"

[dependencies]
MoveStdlib = { local = "../move_stdlib" }
MoveNursery = { local = "../move_nursery" }

[addresses]
std = "0x1"
initia_std = "0x1"
initia_hooks = "0x2"
relayer = "0x3d18d54532fc42e567090852db6eb21fa528f952"
cafe = "0xcafe"
init_fa = "0x8e4733bdabcf7d4afc3d14f0dd46c9bf52fb0fce9e4b996c939e195b8bc891d9"
