[package]
name = "InitiaHooks"
version = "1.0.0"

[dependencies]
MoveStdlib = { local = "../move_stdlib" }
MoveNursery = { local = "../move_nursery" }
InitiaStdlib = { local = "../initia_stdlib" }

[addresses]
std = "0x1"
initia_hook = "0x2"
