use std::{env::current_dir, fs::File};

use serde_generate::{golang::CodeGenerator, CodeGeneratorConfig, Encoding};
use serde_reflection::{Tracer, TracerConfig};

use initia_types::{
    access_path::DataPath,
    account::Account,
    cosmos::{CosmosCoin, CosmosMessage, IBCFee, IBCHeight, IBCMessage, StakingMessage},
    entry_function::EntryFunction,
    env::Env,
    gas_usage::GasUsage,
    module::ModuleBundle,
    result::ExecutionResult,
    script::Script,
    staking_change_set::StakingDelta,
    table::TableInfo,
    view_function::ViewFunction,
    write_set::{WriteOp, WriteSet},
};
use move_core_types::{
    account_address::AccountAddress,
    identifier::Identifier,
    language_storage::{ModuleId, ResourceKey, StructTag, TypeTag},
};

fn main() {
    let mut tracer = Tracer::new(TracerConfig::default());
    tracer.trace_simple_type::<Identifier>().unwrap();
    tracer.trace_simple_type::<StructTag>().unwrap();
    tracer.trace_simple_type::<TypeTag>().unwrap();
    tracer.trace_simple_type::<ModuleId>().unwrap();
    tracer.trace_simple_type::<ResourceKey>().unwrap();
    tracer.trace_simple_type::<AccountAddress>().unwrap();
    tracer.trace_simple_type::<StakingDelta>().unwrap();
    tracer.trace_simple_type::<CosmosCoin>().unwrap();
    tracer.trace_simple_type::<IBCHeight>().unwrap();
    tracer.trace_simple_type::<IBCMessage>().unwrap();
    tracer.trace_simple_type::<IBCFee>().unwrap();
    tracer.trace_simple_type::<StakingMessage>().unwrap();
    tracer.trace_simple_type::<CosmosMessage>().unwrap();
    tracer.trace_simple_type::<Account>().unwrap();
    tracer.trace_simple_type::<GasUsage>().unwrap();
    tracer.trace_simple_type::<ExecutionResult>().unwrap();
    tracer.trace_simple_type::<EntryFunction>().unwrap();
    tracer.trace_simple_type::<ViewFunction>().unwrap();
    tracer.trace_simple_type::<ModuleBundle>().unwrap();
    tracer.trace_simple_type::<Script>().unwrap();
    tracer.trace_simple_type::<DataPath>().unwrap();
    tracer.trace_simple_type::<WriteOp>().unwrap();
    tracer.trace_simple_type::<WriteSet>().unwrap();
    tracer.trace_simple_type::<Env>().unwrap();
    tracer.trace_simple_type::<TableInfo>().unwrap();

    let registry = tracer.registry().unwrap();

    let root = current_dir().unwrap();
    let buffer = File::create(root.join("types/bcs.go")).unwrap();

    // Create class definitions in Go
    // CodeGenerator doesn't have function to put headline comments.. so we have to use this tricky method.
    let config = CodeGeneratorConfig::new("types\n\n//\n// *DO NOT MODIFY THIS FILE!*\n// This is auto-generated by generate-bcs-go.\n//".to_string())
        .with_encodings(vec![Encoding::Bcs]);
    let generator = CodeGenerator::new(&config);
    generator.output(&mut &buffer, &registry).unwrap();
}
