name: Lint
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**.rs"
  push:
    branches:
      - main
      - "release/*"
    paths:
      - "**.rs"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: rust lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make free space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Install latest rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            crates/move-test/build/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Rustfmt
        run: |
          cargo fmt --all
      - name: Clippy
        run: |
          cargo clippy --all --all-targets -- -D warnings

