/* (c) 2024 initia labs. Licensed under BUSL-1.1 */

#ifndef __LIBMOVEVM__
#define __LIBMOVEVM__

/* Generated with cbindgen:0.26.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>


typedef struct {

} vm_t;

typedef struct {
  uint8_t _private[0];
} api_t;

typedef struct {
  int32_t (*query)(const api_t*,
                   U8SliceView,
                   uint64_t,
                   UnmanagedVector*,
                   uint64_t*,
                   UnmanagedVector*);
  int32_t (*get_account_info)(const api_t*,
                              U8SliceView,
                              bool*,
                              uint64_t*,
                              uint64_t*,
                              uint8_t*,
                              bool*,
                              UnmanagedVector*);
  int32_t (*amount_to_share)(const api_t*,
                             U8SliceView,
                             U8SliceView,
                             uint64_t,
                             UnmanagedVector*,
                             UnmanagedVector*);
  int32_t (*share_to_amount)(const api_t*,
                             U8SliceView,
                             U8SliceView,
                             U8SliceView,
                             uint64_t*,
                             UnmanagedVector*);
  int32_t (*unbond_timestamp)(const api_t*, uint64_t*, UnmanagedVector*);
  int32_t (*get_price)(const api_t*,
                       U8SliceView,
                       UnmanagedVector*,
                       uint64_t*,
                       uint64_t*,
                       UnmanagedVector*);
} GoApi_vtable;

typedef struct {
  const api_t *state;
  GoApi_vtable vtable;
} GoApi;

vm_t *allocate_vm(ByteSliceView config_payload);

UnmanagedVector decode_module_bytes(UnmanagedVector *errmsg, ByteSliceView module_bytes);

UnmanagedVector decode_move_resource(Db db,
                                     UnmanagedVector *errmsg,
                                     ByteSliceView struct_tag,
                                     ByteSliceView resource_bytes);

UnmanagedVector decode_move_value(Db db,
                                  UnmanagedVector *errmsg,
                                  ByteSliceView type_tag,
                                  ByteSliceView value_bytes);

UnmanagedVector decode_script_bytes(UnmanagedVector *errmsg, ByteSliceView script_bytes);

UnmanagedVector execute_authenticate(vm_t *vm_ptr,
                                     uint64_t *gas_balance_ptr,
                                     Db db,
                                     GoApi api,
                                     ByteSliceView env_payload,
                                     ByteSliceView sender,
                                     ByteSliceView authenticate_payload,
                                     UnmanagedVector *errmsg);

UnmanagedVector execute_contract(vm_t *vm_ptr,
                                 uint64_t *gas_balance_ptr,
                                 Db db,
                                 GoApi api,
                                 ByteSliceView env_payload,
                                 ByteSliceView senders,
                                 ByteSliceView entry_function_payload,
                                 UnmanagedVector *errmsg);

UnmanagedVector execute_script(vm_t *vm_ptr,
                               uint64_t *gas_balance_ptr,
                               Db db,
                               GoApi api,
                               ByteSliceView env_payload,
                               ByteSliceView senders,
                               ByteSliceView script_payload,
                               UnmanagedVector *errmsg);

UnmanagedVector execute_view_function(vm_t *vm_ptr,
                                      uint64_t *gas_balance_ptr,
                                      Db db,
                                      GoApi api,
                                      ByteSliceView env_payload,
                                      ByteSliceView view_function_payload,
                                      UnmanagedVector *errmsg);

UnmanagedVector initialize(vm_t *vm_ptr,
                           Db db,
                           GoApi api,
                           ByteSliceView env_payload,
                           ByteSliceView module_bundle_payload,
                           ByteSliceView allowed_publishers_payload,
                           UnmanagedVector *errmsg);

UnmanagedVector parse_struct_tag(UnmanagedVector *errmsg, ByteSliceView struct_tag_str);

UnmanagedVector read_module_info(UnmanagedVector *errmsg, ByteSliceView compiled);

void release_vm(vm_t *vm);

UnmanagedVector stringify_struct_tag(UnmanagedVector *errmsg, ByteSliceView struct_tag);

#endif /* __LIBMOVEVM__ */
